#![no_std]

mod errors;
mod prescription;
mod storage;
mod verifier;

use soroban_sdk::{contract, contractimpl, Address, Bytes, BytesN, Env, Symbol};

use errors::ContractError;
use prescription::PrescriptionCommitment;
use storage::{StorageKey, TTL_BUMP_TARGET, TTL_BUMP_THRESHOLD};
use verifier::verify_ultrahonk_proof;

// ─── RBAC cross-contract interface (backed by OZ stellar-access) ─────────────
// trust_leaf_rbac uses OpenZeppelin's AccessControl storage. We call its
// public `has_role(bool)` API which wraps OZ's `Option<u32>` return.
soroban_sdk::contractclient!(RbacClient, "trust-leaf-rbac");

/// Cross-contract role check using OZ-backed RBAC contract.
fn rbac_has_role(env: &Env, rbac_id: &Address, account: &Address, role: &Symbol) -> bool {
    RbacClient::new(env, rbac_id).has_role(account, role)
}

/// Require `caller` to hold `role` in the shared RBAC contract.
/// Calls `require_auth()` before the role check.
fn require_role(
    env: &Env,
    rbac_id: &Address,
    caller: &Address,
    role: &Symbol,
) -> Result<(), ContractError> {
    caller.require_auth();
    if !rbac_has_role(env, rbac_id, caller, role) {
        return Err(ContractError::Unauthorized);
    }
    Ok(())
}

// ─── Contract ─────────────────────────────────────────────────────────────────

#[contract]
pub struct TrustLeafZkMedical;

#[contractimpl]
impl TrustLeafZkMedical {
    // ─── Initialization ────────────────────────────────────────────────

    /// Initialize the ZK medical contract.
    ///
    /// # Arguments
    /// * `rbac_contract` — Deployed RBAC contract address
    /// * `vk_hash`       — SHA-256 of the UltraHonk verification key bytes
    ///                     (generated by `bb write_vk` and hashed off-chain)
    pub fn initialize(
        env: Env,
        rbac_contract: Address,
        vk_hash: BytesN<32>,
    ) -> Result<(), ContractError> {
        if env.storage().instance().has(&StorageKey::Initialized) {
            return Err(ContractError::AlreadyInitialized);
        }
        env.storage()
            .instance()
            .set(&StorageKey::RbacContract, &rbac_contract);
        env.storage()
            .instance()
            .set(&StorageKey::VkHash, &vk_hash);
        env.storage()
            .instance()
            .set(&StorageKey::Initialized, &true);
        env.storage()
            .instance()
            .extend_ttl(TTL_BUMP_THRESHOLD, TTL_BUMP_TARGET);

        env.events().publish(
            (Symbol::new(&env, "ZkMedInit"),),
            (rbac_contract, vk_hash),
        );

        Ok(())
    }

    // ─── Doctor: issue prescription ────────────────────────────────────

    /// Submit a ZK prescription commitment on-chain.
    /// Only callable by accounts with DOCTOR_ROLE.
    ///
    /// # Arguments
    /// * `doctor`               — Doctor's address (require_auth'd)
    /// * `commitment_hash`      — Poseidon2(hash(patient_rut), nonce)
    /// * `authorized_dispensary`— Stellar address of the dispensary allowed to redeem
    /// * `expires_at`           — Ledger timestamp after which the prescription is invalid
    pub fn submit_commitment(
        env: Env,
        doctor: Address,
        commitment_hash: BytesN<32>,
        authorized_dispensary: Address,
        expires_at: u64,
    ) -> Result<(), ContractError> {
        let rbac = Self::get_rbac(&env)?;
        require_role(&env, &rbac, &doctor, &Symbol::new(&env, "DOCTOR"))?;

        let key = StorageKey::Commitment(commitment_hash.clone());
        if env.storage().persistent().has(&key) {
            return Err(ContractError::CommitmentAlreadyExists);
        }

        let record = PrescriptionCommitment {
            commitment_hash: commitment_hash.clone(),
            authorized_dispensary: authorized_dispensary.clone(),
            issued_by: doctor.clone(),
            issued_at: env.ledger().timestamp(),
            expires_at,
            is_used: false,
            is_revoked: false,
        };

        env.storage().persistent().set(&key, &record);
        env.storage()
            .persistent()
            .extend_ttl(&key, TTL_BUMP_THRESHOLD, TTL_BUMP_TARGET);

        env.events().publish(
            (Symbol::new(&env, "CommitSubmit"), commitment_hash.clone()),
            (doctor, authorized_dispensary, expires_at),
        );

        Ok(())
    }

    // ─── Patient: redeem prescription ──────────────────────────────────

    /// Verify a ZK proof and consume the prescription (mark as used).
    ///
    /// This is the heart of the ZK system. The patient's ZK proof proves they
    /// know the pre-image of the commitment (their RUT + nonce) without
    /// revealing either on-chain.
    ///
    /// # Arguments
    /// * `caller`          — The dispensary's address (require_auth'd).
    ///                       The dispensary calls this on behalf of the patient.
    /// * `commitment_hash` — Identifies which prescription to consume
    /// * `nullifier`       — Poseidon2(hash(rut), nonce, 1) — unique spend tag
    /// * `vk_bytes`        — Full UltraHonk VK bytes (validated against stored hash)
    /// * `proof_bytes`     — UltraHonk proof (~2-3 KB) generated by bb.js
    /// * `public_inputs`   — ABI-encoded public inputs: [commitment, nullifier, dispensary]
    ///
    /// # Security flow
    /// 1. Check nullifier not already spent          → prevents double-spend
    /// 2. Check VK hash matches stored hash           → prevents VK substitution
    /// 3. Run bn254_pairing_check                     → validates the proof
    /// 4. Mark nullifier as spent + mark prescription as used (atomic)
    pub fn verify_and_consume(
        env: Env,
        caller: Address,
        commitment_hash: BytesN<32>,
        nullifier: BytesN<32>,
        vk_bytes: Bytes,
        proof_bytes: Bytes,
        public_inputs: Bytes,
    ) -> Result<(), ContractError> {
        // The dispensary must be authorised and authenticated
        let rbac = Self::get_rbac(&env)?;
        require_role(&env, &rbac, &caller, &Symbol::new(&env, "DISPENSARY"))?;

        // ── 1. Double-spend check (BEFORE pairing — avoids paying BN254 on replay) ──
        let nullifier_key = StorageKey::NullifierUsed(nullifier.clone());
        let already_used: bool = env
            .storage()
            .persistent()
            .get(&nullifier_key)
            .unwrap_or(false);
        if already_used {
            return Err(ContractError::AlreadyConsumed);
        }

        // ── 2. Load prescription commitment ───────────────────────────────────────
        let commit_key = StorageKey::Commitment(commitment_hash.clone());
        let mut record: PrescriptionCommitment = env
            .storage()
            .persistent()
            .get(&commit_key)
            .ok_or(ContractError::CommitmentNotFound)?;

        if record.is_revoked {
            return Err(ContractError::CommitmentRevoked);
        }
        if record.is_used {
            return Err(ContractError::AlreadyConsumed);
        }
        if env.ledger().timestamp() > record.expires_at {
            return Err(ContractError::PrescriptionExpired);
        }
        // Caller must be the authorized dispensary
        if caller != record.authorized_dispensary {
            return Err(ContractError::Unauthorized);
        }

        // ── 3. ZK proof verification ──────────────────────────────────────────────
        let stored_vk_hash: BytesN<32> = env
            .storage()
            .instance()
            .get(&StorageKey::VkHash)
            .ok_or(ContractError::NotInitialized)?;

        verify_ultrahonk_proof(
            &env,
            &stored_vk_hash,
            &vk_bytes,
            &proof_bytes,
            &public_inputs,
        )?;

        // ── 4. Atomic state update ────────────────────────────────────────────────
        // Mark nullifier as spent
        env.storage().persistent().set(&nullifier_key, &true);
        env.storage()
            .persistent()
            .extend_ttl(&nullifier_key, TTL_BUMP_THRESHOLD, TTL_BUMP_TARGET);

        // Mark prescription as consumed
        record.is_used = true;
        env.storage().persistent().set(&commit_key, &record);
        env.storage()
            .persistent()
            .extend_ttl(&commit_key, TTL_BUMP_THRESHOLD, TTL_BUMP_TARGET);

        env.events().publish(
            (Symbol::new(&env, "ProofConsumed"), commitment_hash.clone()),
            (caller, nullifier.clone()),
        );

        Ok(())
    }

    // ─── Doctor: revoke prescription ───────────────────────────────────

    /// Revoke an unspent prescription before it expires.
    /// Only the issuing doctor can revoke their own prescription.
    pub fn revoke_commitment(
        env: Env,
        doctor: Address,
        commitment_hash: BytesN<32>,
    ) -> Result<(), ContractError> {
        let rbac = Self::get_rbac(&env)?;
        require_role(&env, &rbac, &doctor, &Symbol::new(&env, "DOCTOR"))?;

        let key = StorageKey::Commitment(commitment_hash.clone());
        let mut record: PrescriptionCommitment = env
            .storage()
            .persistent()
            .get(&key)
            .ok_or(ContractError::CommitmentNotFound)?;

        // Only the issuing doctor can revoke
        if record.issued_by != doctor {
            return Err(ContractError::Unauthorized);
        }
        if record.is_used {
            return Err(ContractError::AlreadyConsumed);
        }

        record.is_revoked = true;
        env.storage().persistent().set(&key, &record);

        env.events().publish(
            (Symbol::new(&env, "CommitRevoked"), commitment_hash),
            (doctor,),
        );

        Ok(())
    }

    // ─── Update VK hash (admin-only) ───────────────────────────────────

    /// Update the stored verification key hash.
    /// Required when the Noir circuit is upgraded (new VK generated).
    pub fn update_vk_hash(
        env: Env,
        caller: Address,
        new_vk_hash: BytesN<32>,
    ) -> Result<(), ContractError> {
        let rbac = Self::get_rbac(&env)?;
        require_role(&env, &rbac, &caller, &Symbol::new(&env, "ADMIN"))?;
        env.storage()
            .instance()
            .set(&StorageKey::VkHash, &new_vk_hash);
        Ok(())
    }

    // ─── Upgrade ──────────────────────────────────────────────────────

    pub fn upgrade(
        env: Env,
        caller: Address,
        new_wasm_hash: BytesN<32>,
    ) -> Result<(), ContractError> {
        let rbac = Self::get_rbac(&env)?;
        require_role(&env, &rbac, &caller, &Symbol::new(&env, "ADMIN"))?;
        env.deployer().update_current_contract_wasm(new_wasm_hash);
        Ok(())
    }

    // ─── Read queries ──────────────────────────────────────────────────

    /// Returns true if the given nullifier has already been spent.
    pub fn is_nullifier_used(env: Env, nullifier: BytesN<32>) -> bool {
        env.storage()
            .persistent()
            .get(&StorageKey::NullifierUsed(nullifier))
            .unwrap_or(false)
    }

    /// Fetch a prescription commitment record.
    pub fn get_commitment(
        env: Env,
        commitment_hash: BytesN<32>,
    ) -> Result<PrescriptionCommitment, ContractError> {
        env.storage()
            .persistent()
            .get(&StorageKey::Commitment(commitment_hash))
            .ok_or(ContractError::CommitmentNotFound)
    }

    // ─── Internal helpers ──────────────────────────────────────────────

    fn get_rbac(env: &Env) -> Result<Address, ContractError> {
        env.storage()
            .instance()
            .get::<StorageKey, Address>(&StorageKey::RbacContract)
            .ok_or(ContractError::NotInitialized)
    }
}

#[cfg(test)]
mod test;
