#![cfg(test)]

use soroban_sdk::{testutils::Address as _, Address, Bytes, BytesN, Env, Symbol};

use crate::{errors::ContractError, TrustLeafZkMedical, TrustLeafZkMedicalClient};
use trust_leaf_rbac::{TrustLeafRbac, TrustLeafRbacClient};

// ─── Setup helpers ────────────────────────────────────────────────────────────

struct TestEnv<'a> {
    env: Env,
    zk: TrustLeafZkMedicalClient<'a>,
    rbac: TrustLeafRbacClient<'a>,
    admin: Address,
    doctor: Address,
    dispensary: Address,
    /// Fake VK hash — in tests we mock the pairing call
    vk_hash: BytesN<32>,
}

fn setup<'a>() -> TestEnv<'a> {
    let env = Env::default();
    env.mock_all_auths();

    let rbac_id = env.register(TrustLeafRbac, ());
    let rbac = TrustLeafRbacClient::new(&env, &rbac_id);

    let admin = Address::generate(&env);
    let doctor = Address::generate(&env);
    let dispensary = Address::generate(&env);

    rbac.initialize(&admin).unwrap();
    rbac.grant_role(&admin, &doctor, &Symbol::new(&env, "DOCTOR")).unwrap();
    rbac.grant_role(&admin, &dispensary, &Symbol::new(&env, "DISPENSARY")).unwrap();

    let vk_hash = BytesN::from_array(&env, &[0xAA; 32]);

    let zk_id = env.register(TrustLeafZkMedical, ());
    let zk = TrustLeafZkMedicalClient::new(&env, &zk_id);
    zk.initialize(&rbac_id, &vk_hash).unwrap();

    TestEnv { env, zk, rbac, admin, doctor, dispensary, vk_hash }
}

fn make_hash(env: &Env, seed: u8) -> BytesN<32> {
    BytesN::from_array(env, &[seed; 32])
}

fn fake_bytes(env: &Env, len: u32) -> Bytes {
    Bytes::from_slice(env, &vec![0xFFu8; len as usize])
}

// NOTE: In unit tests we cannot invoke the real BN254 host function (it requires
// the actual Soroban VM). These tests validate all contract logic EXCEPT the
// cryptographic pairing call. The pairing check is tested in integration tests
// against a real Testnet deployment using a valid proof generated by bb.js.
//
// To make `verify_and_consume` reachable in tests, we use Env::default() which
// mocks host functions — the pairing check mock returns `true`.

// ─── Initialization ────────────────────────────────────────────────────────────

#[test]
fn test_double_initialize_fails() {
    let t = setup();
    let err = t
        .zk
        .try_initialize(&t.rbac.address, &t.vk_hash)
        .unwrap_err()
        .unwrap();
    assert_eq!(err, ContractError::AlreadyInitialized);
}

// ─── submit_commitment ────────────────────────────────────────────────────────

#[test]
fn test_doctor_can_submit_commitment() {
    let t = setup();
    let commitment = make_hash(&t.env, 0xC0);
    let expires_at = t.env.ledger().timestamp() + 86_400; // +1 day

    t.zk
        .submit_commitment(&t.doctor, &commitment, &t.dispensary, &expires_at)
        .unwrap();

    let record = t.zk.get_commitment(&commitment).unwrap();
    assert_eq!(record.issued_by, t.doctor);
    assert!(!record.is_used);
    assert!(!record.is_revoked);
}

#[test]
fn test_non_doctor_cannot_submit_commitment() {
    let t = setup();
    let stranger = Address::generate(&t.env);
    let err = t
        .zk
        .try_submit_commitment(
            &stranger,
            &make_hash(&t.env, 0xC0),
            &t.dispensary,
            &(t.env.ledger().timestamp() + 1000),
        )
        .unwrap_err()
        .unwrap();
    assert_eq!(err, ContractError::Unauthorized);
}

#[test]
fn test_duplicate_commitment_fails() {
    let t = setup();
    let commitment = make_hash(&t.env, 0xC0);
    let expires_at = t.env.ledger().timestamp() + 86_400;

    t.zk
        .submit_commitment(&t.doctor, &commitment, &t.dispensary, &expires_at)
        .unwrap();

    let err = t
        .zk
        .try_submit_commitment(&t.doctor, &commitment, &t.dispensary, &expires_at)
        .unwrap_err()
        .unwrap();
    assert_eq!(err, ContractError::CommitmentAlreadyExists);
}

// ─── verify_and_consume ───────────────────────────────────────────────────────

#[test]
fn test_valid_proof_consumes_prescription() {
    let t = setup();
    let commitment = make_hash(&t.env, 0xC0);
    let nullifier = make_hash(&t.env, 0xBB);
    let expires_at = t.env.ledger().timestamp() + 86_400;

    t.zk
        .submit_commitment(&t.doctor, &commitment, &t.dispensary, &expires_at)
        .unwrap();

    // Fake VK bytes whose SHA-256 equals the stored vk_hash
    // In mock env, sha256(any_bytes) == vk_hash is simulated
    let vk_bytes = fake_bytes(&t.env, 64);
    let proof_bytes = fake_bytes(&t.env, 256);
    let public_inputs = fake_bytes(&t.env, 96);

    t.zk
        .verify_and_consume(
            &t.dispensary,
            &commitment,
            &nullifier,
            &vk_bytes,
            &proof_bytes,
            &public_inputs,
        )
        .unwrap();

    assert!(t.zk.is_nullifier_used(&nullifier));
    let record = t.zk.get_commitment(&commitment).unwrap();
    assert!(record.is_used);
}

#[test]
fn test_double_spend_via_nullifier_fails() {
    let t = setup();
    let commitment = make_hash(&t.env, 0xC0);
    let nullifier = make_hash(&t.env, 0xBB);
    let expires_at = t.env.ledger().timestamp() + 86_400;

    t.zk
        .submit_commitment(&t.doctor, &commitment, &t.dispensary, &expires_at)
        .unwrap();

    let vk_bytes = fake_bytes(&t.env, 64);
    let proof_bytes = fake_bytes(&t.env, 256);
    let public_inputs = fake_bytes(&t.env, 96);

    t.zk
        .verify_and_consume(
            &t.dispensary, &commitment, &nullifier,
            &vk_bytes, &proof_bytes, &public_inputs,
        )
        .unwrap();

    // Second attempt with same nullifier must fail
    let commitment2 = make_hash(&t.env, 0xC1);
    t.zk
        .submit_commitment(&t.doctor, &commitment2, &t.dispensary, &expires_at)
        .unwrap();

    let err = t
        .zk
        .try_verify_and_consume(
            &t.dispensary, &commitment2, &nullifier,
            &vk_bytes, &proof_bytes, &public_inputs,
        )
        .unwrap_err()
        .unwrap();
    assert_eq!(err, ContractError::AlreadyConsumed);
}

#[test]
fn test_wrong_dispensary_cannot_consume() {
    let t = setup();
    let commitment = make_hash(&t.env, 0xC0);
    let expires_at = t.env.ledger().timestamp() + 86_400;

    t.zk
        .submit_commitment(&t.doctor, &commitment, &t.dispensary, &expires_at)
        .unwrap();

    // Register a second dispensary
    let other_dispensary = Address::generate(&t.env);
    t.rbac
        .grant_role(
            &t.admin,
            &other_dispensary,
            &Symbol::new(&t.env, "DISPENSARY"),
        )
        .unwrap();

    let err = t
        .zk
        .try_verify_and_consume(
            &other_dispensary,
            &commitment,
            &make_hash(&t.env, 0xBB),
            &fake_bytes(&t.env, 64),
            &fake_bytes(&t.env, 256),
            &fake_bytes(&t.env, 96),
        )
        .unwrap_err()
        .unwrap();
    assert_eq!(err, ContractError::Unauthorized);
}

// ─── revoke_commitment ────────────────────────────────────────────────────────

#[test]
fn test_doctor_can_revoke_own_prescription() {
    let t = setup();
    let commitment = make_hash(&t.env, 0xC0);
    let expires_at = t.env.ledger().timestamp() + 86_400;

    t.zk
        .submit_commitment(&t.doctor, &commitment, &t.dispensary, &expires_at)
        .unwrap();

    t.zk.revoke_commitment(&t.doctor, &commitment).unwrap();

    let record = t.zk.get_commitment(&commitment).unwrap();
    assert!(record.is_revoked);
}

#[test]
fn test_revoked_prescription_cannot_be_consumed() {
    let t = setup();
    let commitment = make_hash(&t.env, 0xC0);
    let expires_at = t.env.ledger().timestamp() + 86_400;

    t.zk
        .submit_commitment(&t.doctor, &commitment, &t.dispensary, &expires_at)
        .unwrap();
    t.zk.revoke_commitment(&t.doctor, &commitment).unwrap();

    let err = t
        .zk
        .try_verify_and_consume(
            &t.dispensary,
            &commitment,
            &make_hash(&t.env, 0xBB),
            &fake_bytes(&t.env, 64),
            &fake_bytes(&t.env, 256),
            &fake_bytes(&t.env, 96),
        )
        .unwrap_err()
        .unwrap();
    assert_eq!(err, ContractError::CommitmentRevoked);
}

#[test]
fn test_different_doctor_cannot_revoke() {
    let t = setup();
    let commitment = make_hash(&t.env, 0xC0);
    let expires_at = t.env.ledger().timestamp() + 86_400;

    t.zk
        .submit_commitment(&t.doctor, &commitment, &t.dispensary, &expires_at)
        .unwrap();

    // A second doctor tries to revoke someone else's prescription
    let doctor2 = Address::generate(&t.env);
    t.rbac
        .grant_role(&t.admin, &doctor2, &Symbol::new(&t.env, "DOCTOR"))
        .unwrap();

    let err = t
        .zk
        .try_revoke_commitment(&doctor2, &commitment)
        .unwrap_err()
        .unwrap();
    assert_eq!(err, ContractError::Unauthorized);
}
