#!/usr/bin/env bash
# Deploy all TrustLeaf contracts to Stellar Testnet and initialize them.
# Prerequisites:
#   1. Run `bash scripts/build-contracts.sh` first
#   2. Run `bash scripts/setup-testnet.sh` to fund accounts
#   3. Copy .env.testnet.example to .env.testnet and fill in values
#
# Usage: bash scripts/deploy-contracts.sh
set -euo pipefail

NETWORK="testnet"
STELLAR="stellar"
CONTRACTS_DIR="$(cd "$(dirname "$0")/../contracts" && pwd)"
TARGET="$CONTRACTS_DIR/target/wasm32-unknown-unknown/release"

# Load env vars if present
if [ -f "$(dirname "$0")/../.env.testnet" ]; then
  source "$(dirname "$0")/../.env.testnet"
fi

ADMIN_KEY="${ADMIN_KEY:-admin}"

echo "🚀 Deploying TrustLeaf contracts to Testnet..."
echo ""

# ── 1. Deploy RBAC ────────────────────────────────────────────────────────────
echo "  Deploying trust_leaf_rbac..."
RBAC_CONTRACT_ID=$($STELLAR contract deploy \
  --wasm "$TARGET/trust_leaf_rbac.wasm" \
  --source "$ADMIN_KEY" \
  --network $NETWORK)
echo "  ✅ RBAC: $RBAC_CONTRACT_ID"

# Initialize RBAC
ADMIN_ADDRESS=$($STELLAR keys address "$ADMIN_KEY")
$STELLAR contract invoke \
  --id "$RBAC_CONTRACT_ID" \
  --source "$ADMIN_KEY" \
  --network $NETWORK \
  -- initialize \
  --admin "$ADMIN_ADDRESS"
echo "  ✅ RBAC initialized"

# ── 2. Grant roles ────────────────────────────────────────────────────────────
echo ""
echo "  Granting roles..."

GROWER_ADDRESS=$($STELLAR keys address "grower")
DOCTOR_ADDRESS=$($STELLAR keys address "doctor")
DISPENSARY_ADDRESS=$($STELLAR keys address "dispensary")
LAB_ADDRESS=$($STELLAR keys address "lab")

for role_pair in "grower:GROWER" "doctor:DOCTOR" "dispensary:DISPENSARY" "lab:LAB"; do
  account_key="${role_pair%%:*}"
  role="${role_pair##*:}"
  account_addr=$($STELLAR keys address "$account_key")

  $STELLAR contract invoke \
    --id "$RBAC_CONTRACT_ID" \
    --source "$ADMIN_KEY" \
    --network $NETWORK \
    -- grant_role \
    --caller "$ADMIN_ADDRESS" \
    --account "$account_addr" \
    --role "$role"
  echo "    ✅ Granted $role to $account_key ($account_addr)"
done

# ── 3. Deploy Traceability ────────────────────────────────────────────────────
echo ""
echo "  Deploying trust_leaf_traceability..."
TRC_CONTRACT_ID=$($STELLAR contract deploy \
  --wasm "$TARGET/trust_leaf_traceability.wasm" \
  --source "$ADMIN_KEY" \
  --network $NETWORK)
echo "  ✅ Traceability: $TRC_CONTRACT_ID"

$STELLAR contract invoke \
  --id "$TRC_CONTRACT_ID" \
  --source "$ADMIN_KEY" \
  --network $NETWORK \
  -- initialize \
  --rbac_contract "$RBAC_CONTRACT_ID"
echo "  ✅ Traceability initialized"

# ── 4. Deploy ZK Medical ──────────────────────────────────────────────────────
echo ""
# Compute VK hash from the generated vk.bin
VK_BIN="$(dirname "$0")/../circuits/blind_prescription/target/vk.bin"
if [ ! -f "$VK_BIN" ]; then
  echo "  ⚠️  vk.bin not found. Run circuits/scripts/generate_vk.sh first."
  echo "  Using placeholder VK hash for now (replace before mainnet)..."
  VK_HASH="0000000000000000000000000000000000000000000000000000000000000000"
else
  # SHA-256 of vk.bin as hex
  VK_HASH=$(sha256sum "$VK_BIN" | awk '{print $1}')
fi

echo "  Deploying trust_leaf_zk_medical (VK hash: $VK_HASH)..."
ZK_CONTRACT_ID=$($STELLAR contract deploy \
  --wasm "$TARGET/trust_leaf_zk_medical.wasm" \
  --source "$ADMIN_KEY" \
  --network $NETWORK)
echo "  ✅ ZK Medical: $ZK_CONTRACT_ID"

$STELLAR contract invoke \
  --id "$ZK_CONTRACT_ID" \
  --source "$ADMIN_KEY" \
  --network $NETWORK \
  -- initialize \
  --rbac_contract "$RBAC_CONTRACT_ID" \
  --vk_hash "$VK_HASH"
echo "  ✅ ZK Medical initialized"

# ── 5. Write contract IDs to .env.contracts ───────────────────────────────────
ENV_FILE="$(dirname "$0")/../.env.contracts"
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy-contracts.sh — $(date)
NEXT_PUBLIC_RBAC_CONTRACT_ID=$RBAC_CONTRACT_ID
NEXT_PUBLIC_TRACEABILITY_CONTRACT_ID=$TRC_CONTRACT_ID
NEXT_PUBLIC_ZK_MEDICAL_CONTRACT_ID=$ZK_CONTRACT_ID
NEXT_PUBLIC_STELLAR_NETWORK=testnet
NEXT_PUBLIC_STELLAR_RPC_URL=https://soroban-testnet.stellar.org
NEXT_PUBLIC_STELLAR_HORIZON_URL=https://horizon-testnet.stellar.org
NEXT_PUBLIC_NETWORK_PASSPHRASE=Test SDF Network ; September 2015
EOF

echo ""
echo "🎉 All contracts deployed! IDs saved to .env.contracts"
echo ""
cat "$ENV_FILE"
