#!/usr/bin/env bash
# Generate TypeScript bindings for all deployed TrustLeaf contracts.
# Requires .env.contracts (generated by deploy-contracts.sh)
# Usage: bash scripts/generate-bindings.sh
set -euo pipefail

if [ ! -f "$(dirname "$0")/../.env.contracts" ]; then
  echo "❌ .env.contracts not found. Run deploy-contracts.sh first."
  exit 1
fi

source "$(dirname "$0")/../.env.contracts"

NETWORK="testnet"
STELLAR="stellar"
BINDINGS_DIR="$(cd "$(dirname "$0")/../bindings" && pwd)"

mkdir -p "$BINDINGS_DIR"

echo "📦 Generating TypeScript bindings..."

declare -A contracts=(
  ["trust-leaf-rbac"]="$NEXT_PUBLIC_RBAC_CONTRACT_ID"
  ["trust-leaf-traceability"]="$NEXT_PUBLIC_TRACEABILITY_CONTRACT_ID"
  ["trust-leaf-zk-medical"]="$NEXT_PUBLIC_ZK_MEDICAL_CONTRACT_ID"
)

for name in "${!contracts[@]}"; do
  id="${contracts[$name]}"
  echo "  Generating bindings for $name ($id)..."
  $STELLAR contract bindings typescript \
    --network $NETWORK \
    --id "$id" \
    --output "$BINDINGS_DIR/$name" \
    --overwrite
  echo "  ✅ $BINDINGS_DIR/$name"
done

echo ""
echo "✅ Bindings generated. Import from '@trustleaf/bindings/<contract-name>'"
